version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-deps:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
          - "major"